# Generated by Django 4.1.1 on 2022-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file',
        ),
        migrations.AddField(
            model_name='upload',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='first_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='last_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='message',
            field=models.TextField(default=False),
        ),
    ]
