# Generated by Django 4.1.1 on 2022-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('stream', models.CharField(default=False, max_length=200)),
                ('appno', models.IntegerField(blank=True, default=None, null=True)),
                ('Fname', models.CharField(default=False, max_length=200)),
                ('Mname', models.CharField(default=False, max_length=200)),
                ('dob', models.DateField(default=False)),
                ('gender', models.CharField(default=False, max_length=50)),
                ('category', models.CharField(default=False, max_length=5)),
                ('subcategory', models.CharField(default=False, max_length=10)),
                ('region', models.CharField(default=False, max_length=50)),
                ('allottedquota', models.CharField(default=False, max_length=10)),
                ('allottedcategory', models.CharField(default=False, max_length=10)),
                ('mobileno', models.IntegerField(blank=True, default=1, null=True)),
                ('emailid', models.EmailField(default=False, max_length=100)),
                ('address', models.CharField(default=False, max_length=200)),
                ('pcm', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
