# Generated by Django 4.1.4 on 2023-05-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sample_admitted_alter_sample_allottedcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='admitted',
            field=models.CharField(default='Not Specified', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='management',
            field=models.CharField(default='Not Specified', max_length=50, null=True),
        ),
    ]
