# Generated by Django 4.1.1 on 2022-10-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sample_delete_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='mobileno',
        ),
        migrations.AddField(
            model_name='sample',
            name='institute',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
