# Generated by Django 4.1.1 on 2022-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_upload_file_upload_email_upload_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
