# Generated by Django 4.1.1 on 2022-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sample_mobileno_sample_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='stream',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='sample',
            name='yearofadmission',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
