# Generated by Django 4.1.1 on 2022-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_upload_email_alter_upload_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
