# Generated by Django 4.1.4 on 2023-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sample_admitted_alter_sample_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='yearofadmission',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
