# Generated by Django 4.1.1 on 2022-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sample_appno'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='rank',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
