# Generated by Django 4.1.4 on 2023-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sample_yearofadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='enrollmentno',
            field=models.IntegerField(blank=True, default='', null=True, unique=True),
        ),
    ]
