# Generated by Django 4.1.1 on 2022-10-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sample_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='yearofadmission',
            field=models.DateField(default=False),
        ),
    ]
