# Generated by Django 4.1.1 on 2022-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sample_yearofadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='rank',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
