# Generated by Django 4.1.1 on 2022-11-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_sample_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sno',
            field=models.IntegerField(default=None),
        ),
    ]
