# Generated by Django 4.1.1 on 2022-12-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_sample_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='allottedquota',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default=False, max_length=10),
        ),
    ]
