# Generated by Django 4.1.1 on 2022-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_sample_allottedquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='allottedcategory',
            field=models.CharField(choices=[('hs', 'HS'), ('os', 'OS'), ('ai', 'AI')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='allottedquota',
            field=models.CharField(choices=[('opno', 'OPNO'), ('scno', 'SCNO'), ('stno', 'STNO'), ('nodf', 'NODF'), ('noph', 'NOPH')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='category',
            field=models.CharField(choices=[('gen', 'GEN'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('ews', 'EWS'), ('aicte', 'AICTE')], default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='region',
            field=models.CharField(choices=[('delhi', 'DELHI'), ('outside delhi', 'OUTSIDE DELHI')], default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='subcategory',
            field=models.CharField(choices=[('defence', 'DEFENCE'), ('jain', 'JAIN'), ('muslim', 'MUSLIM'), ('sikh', 'SIKH'), ('pwd', 'PWD'), ('jk', 'JK')], default=False, max_length=10),
        ),
    ]
