# Generated by Django 4.1.1 on 2022-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_sample_allottedcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='branch',
            new_name='stream',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='institute',
        ),
        migrations.AddField(
            model_name='sample',
            name='aggregate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='fathermobile',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='studentmobile',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
