# Generated by Django 4.1.1 on 2022-12-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_branch_sample_stream_remove_sample_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='type',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('upgraded', 'UPGRADED'), ('le', 'LE')], default=False, max_length=10),
        ),
    ]
